In [1]:
import numpy as np

In [3]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print(v1)
print(type(v1))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
#Scalar multiplication
v3 = 2*v1
print(v1)
print(v3)

[1 2 3]
[2 4 6]


In [5]:
v4 = v1 + v2
print(v1)
print(v2)
print(v4)

[1 2 3]
[4 5 6]
[5 7 9]
