In [1]:
import numpy as np
import numpy.linalg as la

In [3]:
#Generate two 2x2 matrices A, B
#So 1 & 2 are met: divisor is square and #cols A = #rows B
#Verify that determinant is non-zerro
A = np.matrix([[1, 2],[3, 4]])
B = np.matrix([[5, 6],[7, 8]])
B_det = la.det(B)
print(round(B_det,))

-2


In [4]:
#Invert matrix B
B_inv = la.inv(B)
print(B_inv)

[[-4.   3. ]
 [ 3.5 -2.5]]


In [5]:
#For confirmation of inversion, B * B_inv should give identity matrix I
print(B @ B_inv)

[[1. 0.]
 [0. 1.]]


In [6]:
#Multiply them to complete the operation
#There may be two solution so obtain both
print(B_inv @ A)
print(A @ B_inv)

[[ 5.  4.]
 [-4. -3.]]
[[ 3. -2.]
 [ 2. -1.]]
