In [1]:
import numpy as np

In [5]:
A = np.matrix([[1,2],[3,4]])

B = 5 + A

C = A + B

In [9]:
print(A)
print(B)
print(C)
print(type(A))

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[ 7  9]
 [11 13]]
<class 'numpy.matrix'>
